import type { Syllabus } from '@/lib/learn/types';

export const SYLLABUS: Syllabus = {
  language: 'typescript',
  label: 'TypeScript + JavaScript',
  hubDescription:
    'El stack de la web. Aprende JavaScript moderno y dale superpoderes con el sistema de tipos de TypeScript.',
  baseHref: '/learn/typescript',
  chapters: [
    {
      num: '01',
      title: 'Empezar',
      lessons: [
        {
          slug: 'introduccion-a-javascript',
          title: 'Introducción a JavaScript',
          short: 'Introducción a JavaScript',
          chapter: '01',
          num: '01',
          difficulty: 'beginner',
          readingMinutes: 6,
          exercises: 2,
          appliesTo: ['js'],
        },
        {
          slug: 'javascript-vs-typescript',
          title: 'JavaScript vs TypeScript: ¿cuál aprendo primero?',
          short: 'JavaScript vs TypeScript',
          chapter: '01',
          num: '02',
          difficulty: 'beginner',
          readingMinutes: 7,
          exercises: 0,
          appliesTo: ['js', 'ts'],
        },
        {
          slug: 'tu-primer-programa',
          title: 'Tu primer programa: "Hola, mundo"',
          short: 'Tu primer programa',
          chapter: '01',
          num: '03',
          difficulty: 'beginner',
          readingMinutes: 5,
          exercises: 3,
          appliesTo: ['js', 'ts'],
        },
        {
          slug: 'configurar-el-editor',
          title: 'Configurar el editor y el entorno',
          short: 'Configurar el editor',
          chapter: '01',
          num: '04',
          difficulty: 'beginner',
          readingMinutes: 8,
          exercises: 0,
          appliesTo: ['js', 'ts'],
        },
      ],
    },
    {
      num: '02',
      title: 'Sintaxis',
      lessons: [
        {
          slug: 'variables',
          title: 'Variables: let, const y por qué var ya no se usa',
          short: 'Variables: let, const, var',
          chapter: '02',
          num: '01',
          difficulty: 'beginner',
          readingMinutes: 8,
          exercises: 5,
          appliesTo: ['js', 'ts'],
        },
        {
          slug: 'tipos-primitivos',
          title: 'Tipos primitivos: string, number, boolean, null, undefined',
          short: 'Tipos primitivos',
          chapter: '02',
          num: '02',
          difficulty: 'beginner',
          readingMinutes: 8,
          exercises: 4,
          appliesTo: ['js', 'ts'],
        },
        {
          slug: 'operadores',
          title: 'Operadores: aritméticos, de comparación y lógicos',
          short: 'Operadores',
          chapter: '02',
          num: '03',
          difficulty: 'beginner',
          readingMinutes: 9,
          exercises: 4,
          appliesTo: ['js', 'ts'],
        },
        {
          slug: 'comentarios-y-formato',
          title: 'Comentarios, formato y convenciones de estilo',
          short: 'Comentarios y formato',
          chapter: '02',
          num: '04',
          difficulty: 'beginner',
          readingMinutes: 4,
          exercises: 2,
          appliesTo: ['js', 'ts'],
        },
        {
          slug: 'plantillas-de-string',
          title: 'Template literals: strings dinámicos con `backticks`',
          short: 'Plantillas de string',
          chapter: '02',
          num: '05',
          difficulty: 'beginner',
          readingMinutes: 6,
          exercises: 3,
          appliesTo: ['js', 'ts'],
        },
        {
          slug: 'arrays-y-objetos',
          title: 'Arrays y objetos: colecciones de datos',
          short: 'Arrays y objetos',
          chapter: '02',
          num: '06',
          difficulty: 'beginner',
          readingMinutes: 9,
          exercises: 5,
          appliesTo: ['js', 'ts'],
        },
      ],
    },
    {
      num: '03',
      title: 'Control de flujo',
      lessons: [
        {
          slug: 'if-else',
          title: 'if / else / else if: tomar decisiones en el código',
          short: 'if / else / else if',
          chapter: '03',
          num: '01',
          difficulty: 'beginner',
          readingMinutes: 7,
          exercises: 4,
          appliesTo: ['js', 'ts'],
        },
        {
          slug: 'switch',
          title: 'switch: múltiples ramas sin anidamiento',
          short: 'switch',
          chapter: '03',
          num: '02',
          difficulty: 'beginner',
          readingMinutes: 6,
          exercises: 3,
          appliesTo: ['js', 'ts'],
        },
        {
          slug: 'operador-ternario',
          title: 'Operador ternario: condiciones en una sola línea',
          short: 'Operador ternario',
          chapter: '03',
          num: '03',
          difficulty: 'intermediate',
          readingMinutes: 5,
          exercises: 3,
          appliesTo: ['js', 'ts'],
        },
        {
          slug: 'for-y-for-of',
          title: 'for, for…of y for…in: iterar colecciones',
          short: 'for, for…of, for…in',
          chapter: '03',
          num: '04',
          difficulty: 'beginner',
          readingMinutes: 8,
          exercises: 4,
          appliesTo: ['js', 'ts'],
        },
        {
          slug: 'while-y-do-while',
          title: 'while y do…while: bucles basados en condición',
          short: 'while y do…while',
          chapter: '03',
          num: '05',
          difficulty: 'beginner',
          readingMinutes: 5,
          exercises: 3,
          appliesTo: ['js', 'ts'],
        },
      ],
    },
    {
      num: '04',
      title: 'Funciones',
      lessons: [
        {
          slug: 'declaracion-vs-expresion',
          title: 'Declaración vs expresión de función: ¿qué diferencia hay?',
          short: 'Declaración vs expresión',
          chapter: '04',
          num: '01',
          difficulty: 'intermediate',
          readingMinutes: 8,
          exercises: 4,
          appliesTo: ['js', 'ts'],
        },
        {
          slug: 'arrow-functions',
          title: 'Arrow functions: la sintaxis moderna de funciones',
          short: 'Arrow functions',
          chapter: '04',
          num: '02',
          difficulty: 'intermediate',
          readingMinutes: 7,
          exercises: 4,
          appliesTo: ['js', 'ts'],
        },
        {
          slug: 'parametros-y-defaults',
          title: 'Parámetros, valores por defecto y desestructuración',
          short: 'Parámetros y defaults',
          chapter: '04',
          num: '03',
          difficulty: 'intermediate',
          readingMinutes: 7,
          exercises: 4,
          appliesTo: ['js', 'ts'],
        },
        {
          slug: 'rest-y-spread',
          title: 'Rest y spread: el operador ... explicado',
          short: 'Rest y spread',
          chapter: '04',
          num: '04',
          difficulty: 'intermediate',
          readingMinutes: 8,
          exercises: 4,
          appliesTo: ['js', 'ts'],
        },
        {
          slug: 'closures',
          title: 'Closures: funciones que recuerdan su entorno',
          short: 'Closures',
          chapter: '04',
          num: '05',
          difficulty: 'advanced',
          readingMinutes: 12,
          exercises: 5,
          pro: true,
          appliesTo: ['js', 'ts'],
        },
      ],
    },
    {
      num: '05',
      title: 'TypeScript',
      lessons: [
        {
          slug: 'tipado-basico',
          title: 'Tipado básico: anotaciones de tipo en variables y funciones',
          short: 'Tipado básico',
          chapter: '05',
          num: '01',
          difficulty: 'beginner',
          readingMinutes: 8,
          exercises: 4,
          appliesTo: ['ts'],
        },
        {
          slug: 'interfaces-y-types',
          title: 'Interfaces y types: modelar la forma de los datos',
          short: 'Interfaces y types',
          chapter: '05',
          num: '02',
          difficulty: 'intermediate',
          readingMinutes: 10,
          exercises: 5,
          appliesTo: ['ts'],
        },
        {
          slug: 'unions-e-intersecciones',
          title: 'Unions e intersecciones: combinar tipos con | y &',
          short: 'Unions e intersecciones',
          chapter: '05',
          num: '03',
          difficulty: 'intermediate',
          readingMinutes: 10,
          exercises: 4,
          appliesTo: ['ts'],
        },
        {
          slug: 'genericos',
          title: 'Genéricos: código reutilizable con tipos flexibles',
          short: 'Genéricos',
          chapter: '05',
          num: '04',
          difficulty: 'advanced',
          readingMinutes: 14,
          exercises: 5,
          pro: true,
          appliesTo: ['ts'],
        },
        {
          slug: 'narrowing-y-type-guards',
          title: 'Narrowing y type guards: reducir tipos en tiempo de ejecución',
          short: 'Narrowing y type guards',
          chapter: '05',
          num: '05',
          difficulty: 'intermediate',
          readingMinutes: 10,
          exercises: 4,
          appliesTo: ['ts'],
        },
      ],
    },
  ],
};
